default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: signa_development

test: &test
  <<: *default
  database: signa_test

production:
  <<: *default
  database: signa_production
  username: postgres
  password: postgres

cucumber:
  <<: *test